changelog:
  exclude:
    labels:
      - Merge
  categories:
    - title: Features
      labels:
        - feat
    - title: Fixes
      labels:
        - fix
    - title: Improve
      labels:
        - refactor
        - improve
    - title: Other
      labels:
        - "*"